spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/library
    username: postgres
    password: postgres

jwt:
  secret:
    key: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"